- app/src/main/java/eu/kanade/domain/track/interactor/SyncChapterProgressWithTrack.kt
- app/src/main/java/eu/kanade/domain/track/service/TrackPreferences.kt
- app/src/main/java/eu/kanade/presentation/browse/RelatedMangasScreen.kt
- app/src/main/java/eu/kanade/presentation/browse/components/RelatedMangasComfortableGrid.kt
- app/src/main/java/eu/kanade/presentation/browse/components/RelatedMangasCompactGrid.kt
- app/src/main/java/eu/kanade/presentation/browse/components/RelatedMangasList.kt
- app/src/main/java/eu/kanade/presentation/manga/components/RelatedMangas.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
- app/src/main/res/raw/changelog_debug.xml
- app/src/main/res/raw/changelog_release.xml
- domain/src/main/java/tachiyomi/domain/source/model/StubSource.kt
- i18n-sy/src/commonMain/resources/MR/base/strings.xml
- i18n/src/commonMain/resources/MR/base/strings.xml
- source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/CatalogueSource.kt
- source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/Source.kt
- source-api/src/commonMain/kotlin/eu/kanade/tachiyomi/source/online/HttpSource.kt
> Preview r8926

- i18n-sy/src/commonMain/resources/MR/zh-rTW/strings.xml
add G-sync+Improve some translations
> Update TW strings.xml  

- app/src/main/java/exh/ui/metadata/adapters/EHentaiDescriptionAdapter.kt
- app/src/main/java/exh/ui/metadata/adapters/EightMusesDescriptionAdapter.kt
- app/src/main/java/exh/ui/metadata/adapters/HBrowseDescriptionAdapter.kt
- app/src/main/java/exh/ui/metadata/adapters/MangaDexDescriptionAdapter.kt
- app/src/main/java/exh/ui/metadata/adapters/MetadataUIUtil.kt
- app/src/main/java/exh/ui/metadata/adapters/NHentaiDescriptionAdapter.kt
- app/src/main/java/exh/ui/metadata/adapters/PururinDescriptionAdapter.kt
- app/src/main/java/exh/ui/metadata/adapters/TsuminoDescriptionAdapter.kt
- app/src/main/java/exh/util/SourceTagsUtil.kt
- app/src/main/res/layout/description_adapter_8m.xml
- app/src/main/res/layout/description_adapter_eh.xml
- app/src/main/res/layout/description_adapter_hb.xml
- app/src/main/res/layout/description_adapter_md.xml
- app/src/main/res/layout/description_adapter_nh.xml
- app/src/main/res/layout/description_adapter_pu.xml
- app/src/main/res/layout/description_adapter_ts.xml
- source-api/src/commonMain/kotlin/exh/metadata/metadata/EHentaiSearchMetadata.kt
- source-api/src/commonMain/kotlin/exh/metadata/metadata/EightMusesSearchMetadata.kt
- source-api/src/commonMain/kotlin/exh/metadata/metadata/HBrowseSearchMetadata.kt
- source-api/src/commonMain/kotlin/exh/metadata/metadata/NHentaiSearchMetadata.kt
- source-api/src/commonMain/kotlin/exh/metadata/metadata/PururinSearchMetadata.kt
- source-api/src/commonMain/kotlin/exh/metadata/metadata/TsuminoSearchMetadata.kt
> improve delegated's Metadata view

- app/src/main/java/eu/kanade/tachiyomi/data/sync/service/GoogleDriveSyncService.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
- config/detekt/baseline.xml
> improvement

- gradle/libs.versions.toml
Reverts komikku-app/komikku#146
> Revert "fix(deps): update dependency io.nlopez.compose.rules:detekt to v0.4.5"

- app/src/main/java/eu/kanade/presentation/browse/SourcesScreen.kt
- app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
- app/src/main/java/eu/kanade/presentation/manga/components/MangaInfoHeader.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt
- i18n-kmk/src/commonMain/moko-resources/ar/strings.xml
- i18n-kmk/src/commonMain/moko-resources/base/strings.xml
- i18n-kmk/src/commonMain/moko-resources/cs/strings.xml
- i18n-kmk/src/commonMain/moko-resources/da/strings.xml
- i18n-kmk/src/commonMain/moko-resources/de/strings.xml
- i18n-kmk/src/commonMain/moko-resources/el/strings.xml
- i18n-kmk/src/commonMain/moko-resources/es/strings.xml
- i18n-kmk/src/commonMain/moko-resources/fi/strings.xml
- i18n-kmk/src/commonMain/moko-resources/fr/strings.xml
- i18n-kmk/src/commonMain/moko-resources/it/strings.xml
- i18n-kmk/src/commonMain/moko-resources/ja/strings.xml
- i18n-kmk/src/commonMain/moko-resources/nl/strings.xml
- i18n-kmk/src/commonMain/moko-resources/pl/strings.xml
- i18n-kmk/src/commonMain/moko-resources/pt-rBR/strings.xml
- i18n-kmk/src/commonMain/moko-resources/pt/strings.xml
- i18n-kmk/src/commonMain/moko-resources/ro/strings.xml
- i18n-kmk/src/commonMain/moko-resources/ru/strings.xml
- i18n-kmk/src/commonMain/moko-resources/sv/strings.xml
- i18n-kmk/src/commonMain/moko-resources/uk/strings.xml
- i18n-kmk/src/commonMain/moko-resources/zh-rCN/strings.xml
- i18n-kmk/src/commonMain/moko-resources/zh-rTW/strings.xml
> feat: search entry's title in library

- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadQueueScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/download/DownloadQueueScreenModel.kt
- app/src/main/res/menu/download_single.xml
> feat: Add option to show manga from download queue item

- app/src/main/java/eu/kanade/presentation/browse/MigrationListScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/MigrationFlags.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/design/MigrationBottomSheetDialog.kt
> migraion-copy-delete-downloaded

- app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/BackupRestoreJob.kt
- app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
- app/src/main/java/eu/kanade/tachiyomi/data/sync/SyncDataJob.kt
> fix: canceling job didn't hide status banner

- app/src/main/java/eu/kanade/domain/SYDomainModule.kt
- app/src/main/java/eu/kanade/presentation/browse/FeedScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/models/BackupFeed.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/feed/FeedScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/feed/FeedTab.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/feed/SourceFeedScreenModel.kt
- app/src/main/java/mihon/core/migration/migrations/MoveLatestToFeedMigration.kt
- data/src/main/java/tachiyomi/data/source/FeedSavedSearchMapper.kt
- data/src/main/java/tachiyomi/data/source/FeedSavedSearchRepositoryImpl.kt
- data/src/main/sqldelight/tachiyomi/data/feed_saved_search.sq
- data/src/main/sqldelight/tachiyomi/migrations/33.sqm
- domain/src/main/java/tachiyomi/domain/source/interactor/SwapFeedOrder.kt
- domain/src/main/java/tachiyomi/domain/source/model/FeedSavedSearch.kt
- domain/src/main/java/tachiyomi/domain/source/repository/FeedSavedSearchRepository.kt
- i18n-kmk/src/commonMain/moko-resources/base/strings.xml
allow change feed's order manually by moving up/down
partially implement #130
> feat: change feed's order

- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsLibraryScreen.kt
> 6h auto updates

- .github/workflows/delete_merged_branch.yml
- app/build.gradle.kts
- app/src/main/java/eu/kanade/domain/ui/UiPreferences.kt
- app/src/main/java/eu/kanade/domain/ui/model/AppTheme.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAppearanceScreen.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/appearance/AppCustomThemeColorPickerScreen.kt
- app/src/main/java/eu/kanade/presentation/more/settings/widget/CustomBrightnessSlider.kt
- app/src/main/java/eu/kanade/presentation/more/settings/widget/ThemeColorPickerWidget.kt
- app/src/main/java/eu/kanade/presentation/theme/TachiyomiTheme.kt
- app/src/main/java/eu/kanade/presentation/theme/colorscheme/CustomColorScheme.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/base/delegate/ThemingDelegate.kt
- app/src/main/res/values/themes.xml
- gradle/compose.versions.toml
- gradle/libs.versions.toml
- gradle/sy.versions.toml
- i18n-kmk/src/commonMain/moko-resources/base/strings.xml
- i18n/src/commonMain/moko-resources/base/strings.xml
> Custom themes

- app/src/main/java/eu/kanade/presentation/manga/MangaScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
Also fix the case it was always showing Related Titles on overflow menu.
> Don't show Related Titles for merged entries

- app/src/main/java/eu/kanade/tachiyomi/extension/ExtensionManager.kt
it was flip-flop each time refreshed
> fix: ext obsolete status

- app/src/main/java/eu/kanade/presentation/browse/components/BrowseSourceToolbar.kt
- app/src/main/java/eu/kanade/presentation/manga/components/MangaToolbar.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsAdvancedScreen.kt
> remove option clean invalid downloads

- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreenModel.kt
Make all saved searchs to tabs in BrowseSource
> feat(ui): saved search tabs for browse source

- app/src/main/java/mihon/feature/upcoming/components/calendar/Calendar.kt
- app/src/main/java/mihon/feature/upcoming/components/calendar/CalendarDay.kt
> ui: show number of entries on upcoming screen

- app/src/main/java/eu/kanade/presentation/browse/MigrateMangaScreen.kt
- app/src/main/java/eu/kanade/presentation/browse/MigrateSourceScreen.kt
- app/src/main/java/eu/kanade/presentation/libraryUpdateError/LibraryUpdateErrorScreen.kt
- app/src/main/java/eu/kanade/presentation/manga/components/BaseMangaListItem.kt
- app/src/main/java/eu/kanade/presentation/manga/components/MangaBottomActionMenu.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/advanced/design/PreMigrationScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/manga/MigrateMangaScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/manga/MigrateMangaScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/sources/MigrateSourceTab.kt
- i18n-kmk/src/commonMain/moko-resources/base/strings.xml
- i18n-sy/src/commonMain/moko-resources/base/strings.xml
- Select a range of entries for migration
- Better bottom bar
- Show obsolete sources
> Range-selection for Migration

- app/src/main/java/eu/kanade/tachiyomi/data/updater/AppUpdateDownloadJob.kt
- core/common/src/main/kotlin/eu/kanade/tachiyomi/network/NetworkHelper.kt
* Retry when download failed
* Resume at previous failed download size
* Exponential back-off delay
> App update retry/resume

- core/common/src/main/kotlin/eu/kanade/tachiyomi/network/NetworkHelper.kt
allow set custom timeout or `NetworkHelper.client`
> custom timeout for NetworkHelper.client

- app/src/main/java/exh/debug/DebugFunctions.kt
> fix some debug functions name

- app/build.gradle.kts
- app/src/main/java/eu/kanade/presentation/category/CategoryScreen.kt
- app/src/main/java/eu/kanade/presentation/category/components/CategoryListItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/category/CategoryScreenModel.kt
- domain/src/main/java/tachiyomi/domain/category/interactor/ReorderCategory.kt
- gradle/libs.versions.toml
Drag & Drop to reorder category quickly in Settings/Category screen
> Drag-Drop reordering category 

- app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt
> Fix: duplicate chapters on backup restoring

- app/src/main/java/eu/kanade/presentation/browse/BrowseSourceScreen.kt
- app/src/main/java/eu/kanade/presentation/browse/components/RelatedMangasComfortableGrid.kt
- app/src/main/java/eu/kanade/presentation/browse/components/RelatedMangasCompactGrid.kt
- app/src/main/java/eu/kanade/presentation/browse/components/RelatedMangasList.kt
- app/src/main/java/eu/kanade/presentation/components/BulkSelectionToolbar.kt
- app/src/main/java/eu/kanade/presentation/manga/components/RelatedMangasRow.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/BrowseTab.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/BulkFavoriteScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/feed/FeedScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/feed/FeedTab.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/MigrateSearchScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/search/SourceSearchScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/browse/BrowseSourceScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/feed/SourceFeedScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/feed/SourceFeedScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/GlobalSearchScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/globalsearch/SearchScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/RelatedMangasScreen.kt
- app/src/main/java/exh/md/follows/MangaDexFollowsScreen.kt
- app/src/main/java/exh/md/similar/MangaDexSimilarScreen.kt
- app/src/main/java/exh/recs/RecommendsScreen.kt
- domain/src/main/java/tachiyomi/domain/manga/interactor/NetworkToLocalManga.kt
> Fast browsing

- app/src/main/java/eu/kanade/presentation/browse/FeedOrderScreen.kt
- app/src/main/java/eu/kanade/presentation/browse/FeedScreen.kt
- app/src/main/java/eu/kanade/presentation/browse/SourceFeedOrderScreen.kt
- app/src/main/java/eu/kanade/presentation/browse/SourceFeedScreen.kt
- app/src/main/java/eu/kanade/presentation/browse/components/FeedOrderListItem.kt
- app/src/main/java/eu/kanade/presentation/browse/components/SourceFeedDialogs.kt
- app/src/main/java/eu/kanade/presentation/category/components/CategoryListItem.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/feed/FeedScreenModel.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/feed/FeedTab.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/feed/SourceFeedScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/source/feed/SourceFeedScreenModel.kt
- domain/src/main/java/tachiyomi/domain/category/interactor/HideCategory.kt
- domain/src/main/java/tachiyomi/domain/source/interactor/ReorderFeed.kt
- domain/src/main/java/tachiyomi/domain/source/model/FeedSavedSearchUpdate.kt
> Drag to reorder feeds

- app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt
> Restore chapter's bookmark & oldest  dateUpload from backup

- app/src/main/java/eu/kanade/presentation/more/MoreScreen.kt
- app/src/main/java/eu/kanade/presentation/more/onboarding/GuidesStep.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsDataScreen.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/SettingsTrackingScreen.kt
- app/src/main/java/eu/kanade/presentation/more/settings/screen/about/AboutScreen.kt
- app/src/main/java/eu/kanade/presentation/webview/WebViewScreenContent.kt
- app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateJob.kt
- app/src/main/java/eu/kanade/tachiyomi/data/library/LibraryUpdateNotifier.kt
- app/src/main/java/eu/kanade/tachiyomi/data/updater/AppUpdateNotifier.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/browse/migration/sources/MigrateSourceTab.kt
- core/common/src/main/kotlin/tachiyomi/core/common/Constants.kt
- source-local/src/androidMain/kotlin/tachiyomi/source/local/LocalSource.kt
> update website link

- app/src/main/java/eu/kanade/domain/manga/interactor/SmartSearchMerge.kt
- app/src/main/java/eu/kanade/domain/source/service/SourcePreferences.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/create/BackupCreator.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/create/creators/PreferenceBackupCreator.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/BackupRestorer.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/MangaRestorer.kt
- app/src/main/java/eu/kanade/tachiyomi/data/backup/restore/restorers/PreferenceRestorer.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/MangaScreen.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/merged/EditMergedMangaAdapter.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/merged/EditMergedMangaHolder.kt
- app/src/main/java/eu/kanade/tachiyomi/ui/manga/merged/EditMergedSettingsDialog.kt
- app/src/main/java/exh/EXHMigrations.kt
- app/src/main/java/mihon/core/migration/MigrateUtils.kt
- data/src/main/sqldelight/tachiyomi/data/eh.sq
- data/src/main/sqldelight/tachiyomi/data/merged.sq
- domain/src/main/java/tachiyomi/domain/download/service/DownloadPreferences.kt
- domain/src/main/java/tachiyomi/domain/library/service/LibraryPreferences.kt
- domain/src/main/java/tachiyomi/domain/manga/model/MergedMangaReference.kt
> Backup restoration

- app/src/main/java/exh/recs/sources/ComickPagingSource.kt
> Fix Comick recommendations failed due to empty cover list

- app/src/main/java/exh/ui/batchadd/BatchAddScreen.kt
- i18n-kmk/src/commonMain/moko-resources/base/strings.xml
> Description showing which sources support batch-add

- data/src/main/sqldelight/tachiyomi/migrations/37.sqm
- data/src/main/sqldelight/tachiyomi/view/updatesView.sq
> Hide excluded scanlators from Update view
